name: Run tests and publish report
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Установка JDK"
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 21

      - name: "Запуск тестов"
        run: ./gradlew clean test

      - name: "Загрузка истории отчетов тестирования"
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: "Создание отчета тестирования"
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
          allure_report: allure-report


      - name: "Публикация отчета тестирования"
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history